export const stylesTokensComponents = {
  '--em-actionicon-background': 'var(--em-sem-background--light)',
  '--em-actionicon-background--active': 'var(--em-sem-background--muted)',
  '--em-actionicon-background--hover': 'var(--em-sem-background--subtle)',
  '--em-actionicon-border-radius': 'var(--em-core-border-radius--500)',
  '--em-actionicon-color': 'var(--em-sem-text)',
  '--em-actionicon-color--disabled': 'var(--em-sem-text--subtle)',
  '--em-actionicon-height': 'var(--em-core-size--0800)',
  '--em-actionicon-icon-size': 'var(--em-core-size--0400)',
  '--em-actionicon-padding-left-right': 'var(--em-core-spacing--0050)',
  '--em-actionicon-padding-top-bottom': 'var(--em-core-spacing--0200)',
  '--em-actionicon-width': 'var(--em-core-size--0500)',

  '--em-buttonicon-background--primary': 'var(--em-sem-text--muted)',
  '--em-buttonicon-background--primary--active': 'var(--em-sem-text--neutral)',
  '--em-buttonicon-background--primary--disabled': 'var(--em-sem-background--light)',
  '--em-buttonicon-background--primary--hover': 'var(--em-sem-text)',
  '--em-buttonicon-background--secondary': 'var(--em-sem-background--light)',
  '--em-buttonicon-background--secondary--active': 'var(--em-sem-background--muted)',
  '--em-buttonicon-background--secondary--disabled': 'var(--em-sem-background--light)',
  '--em-buttonicon-background--secondary--hover': 'var(--em-sem-background--subtle)',
  '--em-buttonicon-border-radius': 'var(--em-core-border-radius--500)',
  '--em-buttonicon-color--disabled': 'var(--em-sem-text--subtle)',
  '--em-buttonicon-color--primary': 'var(--em-sem-text--inverted)',
  '--em-buttonicon-color--secondary': 'var(--em-sem-text)',
  '--em-buttonicon-height--medium': 'var(--em-core-size--1000)',
  '--em-buttonicon-height--small': 'var(--em-core-size--0800)',
  '--em-buttonicon-icon-size': 'var(--em-core-size--0400)',
  '--em-buttonicon-padding-left-right--medium': 'var(--em-core-spacing--0300)',
  '--em-buttonicon-padding-left-right--small': 'var(--em-core-spacing--0150)',
  '--em-buttonicon-padding-top-bottom--medium': 'var(--em-core-spacing--0300)',
  '--em-buttonicon-padding-top-bottom--small': 'var(--em-core-spacing--0150)',

  '--em-ghostbutton-background--active': 'var(--em-sem-background--light)',
  '--em-ghostbutton-background--hover': 'var(--em-sem-background)',
  '--em-ghostbutton-border-radius': 'var(--em-core-border-radius--100)',
  '--em-ghostbutton-color': 'var(--em-sem-text)',
  '--em-ghostbutton-color--disabled': 'var(--em-sem-text--subtle)',
  '--em-ghostbutton-font-family': 'var(--em-core-font-family--base)',
  '--em-ghostbutton-font-size': 'var(--em-core-font-size--xs)',
  '--em-ghostbutton-font-weight': 'var(--em-core-font-weight--regular)',
  '--em-ghostbutton-height': 'var(--em-core-size--0500)',
  '--em-ghostbutton-icon-size': 'var(--em-core-size--0400)',
  '--em-ghostbutton-label-padding-left': 'var(--em-core-spacing--0100)',
  '--em-ghostbutton-label-padding-right': 'var(--em-core-spacing--0100)',
  '--em-ghostbutton-line-height': 'var(--em-core-line-height--sm)',
  '--em-ghostbutton-padding': 'var(--em-core-spacing--0050)',
};

type StylesTokensComponents = typeof stylesTokensComponents;
export type StylesTokensComponentsKeys = keyof StylesTokensComponents;
