export const stylesColors = {
  '--em-gray-0': 'rgb(255 255 255)',
  '--em-gray-050': 'rgb(247 247 248)',
  '--em-gray-100': 'rgb(237 237 241)',
  '--em-gray-1000': 'rgb(0 0 0)',
  '--em-gray-200': 'rgb(228 228 234)',
  '--em-gray-300': 'rgb(210 210 213)',
  '--em-gray-400': 'rgb(184 184 189)',
  '--em-gray-500': 'rgb(144 144 152)',
  '--em-gray-600': 'rgb(114 114 121)',
  '--em-gray-700': 'rgb(92 92 102)',
  '--em-gray-800': 'rgb(49 49 61)',
  '--em-gray-900': 'rgb(33 33 41)',
  '--em-orange-050': 'rgb(255 238 230)',
  '--em-orange-100': 'rgb(255 221 204)',
  '--em-orange-200': 'rgb(255 204 179)',
  '--em-orange-300': 'rgb(255 187 153)',
  '--em-orange-400': 'rgb(255 170 128)',
  '--em-orange-500': 'rgb(255 153 102)',
  '--em-orange-600': 'rgb(255 136 77)',
  '--em-orange-700': 'rgb(255 119 51)',
  '--em-orange-800': 'rgb(255 102 26)',
  '--em-orange-900': 'rgb(255 84 0)',
};

const stylesSpacingAndSizes = {
  '--em-height-0': '0px',
  '--em-height-050': '2px',
  '--em-height-100': '4px',
  '--em-height-1000': '40px',
  '--em-height-1200': '48px',
  '--em-height-150': '6px',
  '--em-height-1600': '64px',
  '--em-height-200': '8px',
  '--em-height-2000': '80px',
  '--em-height-300': '12px',
  '--em-height-400': '16px',
  '--em-height-500': '20px',
  '--em-height-600': '24px',
  '--em-height-700': '28px',
  '--em-height-800': '32px',
  '--em-height-900': '36px',
  '--em-margin-0': '0px',
  '--em-margin-050': '2px',
  '--em-margin-100': '4px',
  '--em-margin-1000': '40px',
  '--em-margin-1200': '48px',
  '--em-margin-150': '6px',
  '--em-margin-1600': '64px',
  '--em-margin-200': '8px',
  '--em-margin-2000': '80px',
  '--em-margin-300': '12px',
  '--em-margin-400': '16px',
  '--em-margin-500': '20px',
  '--em-margin-600': '24px',
  '--em-margin-700': '28px',
  '--em-margin-800': '32px',
  '--em-margin-900': '36px',
  '--em-padding-0': '0px',
  '--em-padding-050': '2px',
  '--em-padding-100': '4px',
  '--em-padding-1000': '40px',
  '--em-padding-1200': '48px',
  '--em-padding-150': '6px',
  '--em-padding-1600': '64px',
  '--em-padding-200': '8px',
  '--em-padding-2000': '80px',
  '--em-padding-300': '12px',
  '--em-padding-400': '16px',
  '--em-padding-500': '20px',
  '--em-padding-600': '24px',
  '--em-padding-700': '28px',
  '--em-padding-800': '32px',
  '--em-padding-900': '36px',
  '--em-width-0': '0px',
  '--em-width-050': '2px',
  '--em-width-100': '4px',
  '--em-width-1000': '40px',
  '--em-width-1200': '48px',
  '--em-width-150': '6px',
  '--em-width-1600': '64px',
  '--em-width-200': '8px',
  '--em-width-2000': '80px',
  '--em-width-300': '12px',
  '--em-width-400': '16px',
  '--em-width-500': '20px',
  '--em-width-600': '24px',
  '--em-width-700': '28px',
  '--em-width-800': '32px',
  '--em-width-900': '36px',
};

const stylesBorders = {
  '--em-border-radius-0': '0px',
  '--em-border-radius-050': '2px',
  '--em-border-radius-100': '4px',
  '--em-border-radius-150': '6px',
  '--em-border-radius-200': '8px',
  '--em-border-radius-300': '12px',
  '--em-border-radius-400': '32px',
  '--em-border-radius-500': '9999px',
  '--em-border-width-0': '0px',
  '--em-border-width-default': '1px',
  '--em-border-width-l': '2px',
  '--em-border-width-xl': '4px',
};

const stylesComponents = {
  '--em-background-color-default': 'var(--em-gray-050)',
  '--em-background-color-inverted': 'var(--em-gray-900)',
  '--em-background-color-light': 'var(--em-gray-100)',
  '--em-background-color-muted': 'var(--em-gray-300)',
  '--em-background-color-neutral': 'var(--em-gray-0)',
  '--em-background-color-subtle': 'var(--em-gray-200)',
  '--em-btn-island-background-color-default': 'var(--em-background-color-neutral)',
  '--em-btn-island-border-radius-default': 'var(--em-border-radius-500)',
  '--em-btn-island-padding-default': 'var(--em-padding-200)',
  '--em-calendar-custom-font-color-default': 'var(--em-foreground-color-default)',
  '--em-calendar-custom-font-font-family': 'var(--em-font-family-default)',
  '--em-calendar-custom-font-font-size': 'var(--em-font-size-xs)',
  '--em-calendar-custom-font-font-weight': 'var(--em-font-weight-bold)',
  '--em-calendar-custom-font-line-height': 'var(--em-line-height-sm)',
  '--em-calendar-dates-background-color-day-number-ranged': 'var(--em-background-color-light)',
  '--em-calendar-dates-background-color-day-number-selected': 'var(--em-background-color-inverted)',
  '--em-calendar-dates-font-color-day-name': 'var(--em-foreground-color-muted)',
  '--em-calendar-dates-font-color-day-number-current-month': 'var(--em-foreground-color-default)',
  '--em-calendar-dates-font-color-day-number-previous-month': 'var(--em-foreground-color-subtle)',
  '--em-calendar-dates-font-color-day-number-ranged': 'var(--em-foreground-color-default)',
  '--em-calendar-dates-font-color-day-number-selected': 'var(--em-foreground-color-inverted)',
  '--em-calendar-dates-font-font-family': 'var(--em-font-family-default)',
  '--em-calendar-dates-font-font-size': 'var(--em-font-size-sm)',
  '--em-calendar-dates-font-font-weight': 'var(--em-font-weight-medium)',
  '--em-calendar-dates-font-line-height': 'var(--em-line-height-md)',
  '--em-calendar-nav-background-color-default': 'var(--em-background-color-neutral)',
  '--em-calendar-nav-background-color-hover': 'var(--em-background-color-default)',
  '--em-calendar-nav-background-color-pressed': 'var(--em-background-color-light)',
  '--em-calendar-nav-border-radius-default': 'var(--em-border-radius-200)',
  '--em-calendar-nav-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-calendar-nav-padding-default': 'var(--em-padding-200)',
  '--em-calendar-nav-size-height': 'var(--em-width-800)',
  '--em-calendar-nav-size-width': 'var(--em-width-800)',
  '--em-calendar-view-font-color-default': 'var(--em-foreground-color-default)',
  '--em-calendar-view-font-font-family': 'var(--em-font-family-default)',
  '--em-calendar-view-font-font-size': 'var(--em-font-size-sm)',
  '--em-calendar-view-font-font-weight': 'var(--em-font-weight-medium)',
  '--em-calendar-view-font-line-height': 'var(--em-line-height-md)',
  '--em-calendar-view-padding-default': 'var(--em-padding-200)',
  '--em-card-border-radius-default': 'var(--em-border-radius-400)',
  '--em-card-empty-subtitle-font-color-default': 'var(--em-foreground-color-muted)',
  '--em-card-empty-title-font-color-default': 'var(--em-foreground-color-default)',
  '--em-card-error-font-color-default': 'var(--em-status-error)',
  '--em-card-error-state-icon-color-default': 'var(--em-status-error)',
  '--em-card-error-state-icon-size-height': 'var(--em-height-400)',
  '--em-card-error-state-icon-size-width': 'var(--em-width-400)',
  '--em-card-gap-default': 'var(--em-padding-800)',
  '--em-card-header-padding-default': 'var(--em-padding-400)',
  '--em-card-info-font-font-family': 'var(--em-font-family-default)',
  '--em-card-info-font-line-height': 'var(--em-line-height-md)',
  '--em-card-info-font-size': 'var(--em-font-size-sm)',
  '--em-card-info-font-subtitle-weight': 'var(--em-font-weight-regular)',
  '--em-card-info-font-title-weight': 'var(--em-font-weight-medium)',
  '--em-card-info-padding-default': 'var(--em-padding-300)',
  '--em-card-loader-border-radius-default': 'var(--em-border-radius-500)',
  '--em-card-loader-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-card-loader-icon-size-height': 'var(--em-height-600)',
  '--em-card-loader-icon-size-width': 'var(--em-width-600)',
  '--em-card-loader-padding-default': 'var(--em-padding-100)',
  '--em-card-opacity-default': '90px',
  '--em-card-padding-default': 'var(--em-padding-800)',
  '--em-card-subtitle-color-default': 'var(--em-foreground-color-muted)',
  '--em-card-subtitle-font-font-family': 'var(--em-font-family-default)',
  '--em-card-subtitle-font-line-height': 'var(--em-line-height-l)',
  '--em-card-subtitle-font-size': 'var(--em-font-size-sm)',
  '--em-card-subtitle-font-weight': 'var(--em-font-weight-regular)',
  '--em-card-title-color-default': 'var(--em-foreground-color-default)',
  '--em-card-title-font-font-family': 'var(--em-font-family-default)',
  '--em-card-title-font-line-height': 'var(--em-line-height-l)',
  '--em-card-title-font-size': 'var(--em-font-size-md)',
  '--em-card-title-font-weight': 'var(--em-font-weight-bold)',
  '--em-card-title-padding-default': 'var(--em-padding-400)',
  '--em-category-group-gap-default': 'var(--em-padding-200)',
  '--em-category-group-item-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-category-group-item-label-font-font-family': 'var(--em-font-family-default)',
  '--em-category-group-item-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-category-group-item-label-font-size': 'var(--em-font-size-xs)',
  '--em-category-group-item-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-category-indicator-border-radius-default': 'var(--em-border-radius-500)',
  '--em-category-indicator-color-default': 'var(--em-chart-color-1)',
  '--em-category-indicator-gap-default': 'var(--em-padding-100)',
  '--em-category-indicator-size-height': 'var(--em-width-200)',
  '--em-category-indicator-size-width': 'var(--em-width-200)',
  '--em-cc-card-icon-size-width': 'var(--em-width-200)',
  '--em-line-chart-point-width-default': 'var(--em-width-200)',
  '--em-chart-color-1': 'var(--em-orange-900)',
  '--em-chart-color-10': 'var(--em-orange-050)',
  '--em-chart-color-2': 'var(--em-orange-800)',
  '--em-chart-color-3': 'var(--em-orange-700)',
  '--em-chart-color-4': 'var(--em-orange-600)',
  '--em-chart-color-5': 'var(--em-orange-500)',
  '--em-chart-color-6': 'var(--em-orange-400)',
  '--em-chart-color-7': 'var(--em-orange-300)',
  '--em-chart-color-8': 'var(--em-orange-200)',
  '--em-chart-color-9': 'var(--em-orange-100)',
  '--em-chart-gap-default': 'var(--em-padding-300)',
  '--em-chart-grid-font-color-default': 'var(--em-foreground-color-neutral)',
  '--em-chart-grid-font-color-muted': 'var(--em-foreground-color-muted)',
  '--em-chart-grid-font-color-subtle': 'var(--em-foreground-color-subtle)',
  '--em-chart-grid-font-font-family': 'var(--em-font-family-default)',
  '--em-chart-grid-font-label-weight': 'var(--em-font-weight-regular)',
  '--em-chart-grid-font-line-height': 'var(--em-line-height-sm)',
  '--em-chart-grid-font-subtitle-size': 'var(--em-font-size-xs)',
  '--em-chart-grid-font-title-size': 'var(--em-font-size-sm)',
  '--em-chart-grid-font-title-weight': 'var(--em-font-weight-bold)',
  '--em-chart-grid-line-color-default': 'var(--em-foreground-color-default)',
  '--em-chart-grid-line-color-light': 'var(--em-background-color-light)',
  '--em-chart-grid-line-color-subtle': 'var(--em-foreground-color-subtle)',
  '--em-chart-grid-line-width-0': 'var(--em-border-width-0)',
  '--em-chart-grid-line-width-default': 'var(--em-border-width-default)',
  '--em-chart-grid-line-width-l': 'var(--em-border-width-l)',
  '--em-chart-grid-line-width-xl': 'var(--em-border-width-xl)',
  '--em-chart-grid-padding-default': 'var(--em-padding-200)',
  '--em-chart-grid-padding-lg': 'var(--em-padding-400)',
  '--em-chart-grid-padding-xl': 'var(--em-padding-800)',
  '--em-chart-grid-padding-xs': 'var(--em-padding-100)',
  '--em-chart-grid-tick-lenght-default': 'var(--em-width-100)',
  '--em-chart-grid-tick-width-0': 'var(--em-border-width-0)',
  '--em-chart-grid-tick-width-default': 'var(--em-border-width-default)',
  '--em-chart-grid-tick-width-l': 'var(--em-border-width-l)',
  '--em-chart-grid-tick-width-xl': 'var(--em-border-width-xl)',
  '--em-chart-style-border-radius-0': 'var(--em-border-radius-0)',
  '--em-chart-style-border-radius-default': 'var(--em-border-radius-150)',
  '--em-chart-tooltip-background-color-default': 'var(--em-background-color-inverted)',
  '--em-chart-tooltip-border-radius-default': 'var(--em-border-radius-300)',
  '--em-chart-tooltip-gap-default': 'var(--em-padding-200)',
  '--em-chart-tooltip-label-color-default': 'rgb(255 255 255)',
  '--em-chart-tooltip-padding-default': 'var(--em-padding-400)',
  '--em-chart-tooltip-title-font-font-family': 'var(--em-font-family-default)',
  '--em-chart-tooltip-title-font-line-height': 'var(--em-line-height-md)',
  '--em-chart-tooltip-title-font-size': 'var(--em-font-size-sm)',
  '--em-chart-tooltip-title-font-weight': 'var(--em-font-weight-bold)',
  '--em-checkbox-color-default': 'var(--em-foreground-color-default)',
  '--em-checkbox-size-height': 'var(--em-width-400)',
  '--em-checkbox-size-width': 'var(--em-width-400)',
  '--em-empty-state-background-color-default': 'var(--em-background-color-default)',
  '--em-empty-state-icon-color-default': 'var(--em-foreground-color-muted)',
  '--em-empty-state-icon-size-height': 'var(--em-width-600)',
  '--em-empty-state-icon-size-width': 'var(--em-width-600)',
  '--em-empty-state-opacity-default': '60px',
  '--em-empty-state-padding-default': 'var(--em-padding-400)',
  '--em-empty-state-skeleton-size-min-height': '128px',
  '--em-empty-state-skeleton-size-min-width': '128px',
  '--em-foreground-color-default': 'var(--em-gray-900)',
  '--em-foreground-color-error': 'var(--em-status-error)',
  '--em-foreground-color-inverted': 'var(--em-gray-0)',
  '--em-foreground-color-muted': 'var(--em-gray-700)',
  '--em-foreground-color-neutral': 'var(--em-gray-1000)',
  '--em-foreground-color-subtle': 'var(--em-gray-400)',
  '--em-form-background-color-default': 'var(--em-background-color-neutral)',
  '--em-form-border-radius-default': 'var(--em-border-radius-400)',
  '--em-form-form-font-font-color': 'var(--em-foreground-color-default)',
  '--em-form-form-font-font-family': 'var(--em-font-family-default)',
  '--em-form-form-font-font-size-required': 'var(--em-font-size-xs)',
  '--em-form-form-font-font-size-title': 'var(--em-font-size-sm)',
  '--em-form-form-font-font-weight': 'var(--em-font-weight-regular)',
  '--em-form-form-font-line-height': 'var(--em-line-height-md)',
  '--em-form-group-background-color-hover': 'var(--em-background-color-default)',
  '--em-form-group-border-radius-default': 'var(--em-border-radius-200)',
  '--em-form-group-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-form-group-icon-size-height': 'var(--em-width-400)',
  '--em-form-group-icon-size-width': 'var(--em-width-400)',
  '--em-form-group-padding-default': 'var(--em-padding-200)',
  '--em-form-group-padding-small': 'var(--em-padding-050)',
  '--em-form-header-font-font-color': 'var(--em-foreground-color-default)',
  '--em-form-header-font-font-family': 'var(--em-font-family-default)',
  '--em-form-header-font-font-size': 'var(--em-font-size-md)',
  '--em-form-header-font-font-weight': 'var(--em-font-weight-bold)',
  '--em-form-header-font-line-height': 'var(--em-line-height-md)',
  '--em-form-header-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-form-header-icon-size-height': 'var(--em-width-800)',
  '--em-form-header-icon-size-width': 'var(--em-width-800)',
  '--em-form-padding-default': 'var(--em-padding-400)',
  '--em-form-padding-large': 'var(--em-padding-800)',
  '--em-form-padding-small': 'var(--em-padding-200)',
  '--em-form-section-font-font-color': 'var(--em-foreground-color-default)',
  '--em-form-section-font-font-family': 'var(--em-font-family-default)',
  '--em-form-section-font-font-size': 'var(--em-font-size-md)',
  '--em-form-section-font-font-weight': 'var(--em-font-weight-medium)',
  '--em-form-section-font-line-height': 'var(--em-line-height-md)',
  '--em-ghost-btn-background-color-hover': 'var(--em-background-color-default)',
  '--em-ghost-btn-background-color-pressed': 'var(--em-background-color-light)',
  '--em-ghost-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-ghost-btn-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-ghost-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-ghost-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-ghost-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-ghost-btn-label-color-default': 'var(--em-foreground-color-default)',
  '--em-ghost-btn-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-ghost-btn-label-font-default-font-family': 'var(--em-font-family-default)',
  '--em-ghost-btn-label-font-default-line-height': 'var(--em-line-height-sm)',
  '--em-ghost-btn-label-font-default-size': 'var(--em-font-size-xs)',
  '--em-ghost-btn-label-font-default-weight': 'var(--em-font-weight-regular)',
  '--em-ghost-btn-label-padding-default': 'var(--em-padding-100)',
  '--em-ghost-btn-padding-default': 'var(--em-padding-050)',
  '--em-ghost-btn-size-height': 'var(--em-height-500)',
  '--em-icon-btn-background-color-default': 'var(--em-background-color-light)',
  '--em-icon-btn-background-color-disabled': 'var(--em-background-color-light)',
  '--em-icon-btn-background-color-hover': 'var(--em-background-color-subtle)',
  '--em-icon-btn-background-color-pressed': 'var(--em-background-color-muted)',
  '--em-icon-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-icon-btn-icon-color-call-to-action': 'var(--em-orange-900)',
  '--em-icon-btn-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-icon-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-icon-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-icon-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-icon-btn-padding-bottom': 'var(--em-padding-200)',
  '--em-icon-btn-padding-left': 'var(--em-padding-050)',
  '--em-icon-btn-padding-right': 'var(--em-padding-050)',
  '--em-icon-btn-padding-top': 'var(--em-padding-200)',
  '--em-icon-btn-size-height': 'var(--em-height-800)',
  '--em-icon-btn-size-width': 'var(--em-width-500)',
  '--em-icon-height': 'var(--em-height-400)',
  '--em-icon-width': 'var(--em-width-400)',
  '--em-label-background-color-default': 'var(--em-background-color-neutral)',
  '--em-label-border-radius-default': 'var(--em-border-radius-500)',
  '--em-label-label-font-color-default': 'var(--em-foreground-color-default)',
  '--em-label-label-font-font-family': 'var(--em-font-family-default)',
  '--em-label-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-label-label-font-size': 'var(--em-font-size-xs)',
  '--em-label-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-label-padding-left-right': 'var(--em-padding-100)',
  '--em-label-padding-top-bottom': 'var(--em-padding-050)',
  '--em-lightbox-font-color-default': 'var(--em-foreground-color-inverted)',
  '--em-lightbox-font-font-family': 'var(--em-font-family-default)',
  '--em-lightbox-font-font-size': 'var(--em-font-size-xl)',
  '--em-lightbox-font-font-weight': 'var(--em-font-weight-medium)',
  '--em-lightbox-font-line-height': 'var(--em-line-height-l)',
  '--em-lightbox-padding-default': 'var(--em-padding-400)',
  '--em-pie-chart-donut-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-pie-chart-donut-label-font-line-height': 'var(--em-line-height-md)',
  '--em-pie-chart-donut-label-font-size': 'var(--em-font-size-md)',
  '--em-pie-chart-donut-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-pie-chart-donut-number-color-default': 'var(--em-foreground-color-default)',
  '--em-pie-chart-donut-number-font-line-height': 'var(--em-line-height-xl)',
  '--em-pie-chart-donut-number-font-size': 'var(--em-font-size-xxl)',
  '--em-pie-chart-donut-number-font-weight': 'var(--em-font-weight-bold)',
  '--em-pie-chart-donut-number-gap-default': 'var(--em-padding-200)',
  '--em-primary-btn-background-color-default': 'var(--em-foreground-color-muted)',
  '--em-primary-btn-background-color-disabled': 'var(--em-background-color-light)',
  '--em-primary-btn-background-color-hover': 'var(--em-foreground-color-default)',
  '--em-primary-btn-background-color-pressed': 'var(--em-foreground-color-neutral)',
  '--em-primary-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-primary-btn-icon-color-default': 'var(--em-foreground-color-inverted)',
  '--em-primary-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-primary-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-primary-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-primary-btn-label-color-default': 'var(--em-foreground-color-inverted)',
  '--em-primary-btn-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-primary-btn-label-font-medium-font-family': 'var(--em-font-family-default)',
  '--em-primary-btn-label-font-medium-line-height': 'var(--em-line-height-md)',
  '--em-primary-btn-label-font-medium-size': 'var(--em-font-size-sm)',
  '--em-primary-btn-label-font-medium-weight': 'var(--em-font-weight-bold)',
  '--em-primary-btn-label-font-small-font-family': 'var(--em-font-family-default)',
  '--em-primary-btn-label-font-small-line-height': 'var(--em-line-height-sm)',
  '--em-primary-btn-label-font-small-size': 'var(--em-font-size-xs)',
  '--em-primary-btn-label-font-small-weight': 'var(--em-font-weight-medium)',
  '--em-primary-btn-label-padding-default': 'var(--em-padding-200)',
  '--em-primary-btn-padding-medium-bottom': 'var(--em-padding-300)',
  '--em-primary-btn-padding-medium-left': 'var(--em-padding-300)',
  '--em-primary-btn-padding-medium-right': 'var(--em-padding-300)',
  '--em-primary-btn-padding-medium-top': 'var(--em-padding-300)',
  '--em-primary-btn-padding-small-bottom': 'var(--em-padding-150)',
  '--em-primary-btn-padding-small-left': 'var(--em-padding-150)',
  '--em-primary-btn-padding-small-right': 'var(--em-padding-150)',
  '--em-primary-btn-padding-small-top': 'var(--em-padding-150)',
  '--em-primary-btn-size-medium-height': 'var(--em-height-1000)',
  '--em-primary-btn-size-small-height': 'var(--em-height-800)',
  '--em-radio-color-default': 'var(--em-foreground-color-default)',
  '--em-radio-size-height': 'var(--em-width-400)',
  '--em-radio-size-width': 'var(--em-width-400)',
  '--em-secondary-btn-background-color-default': 'var(--em-background-color-light)',
  '--em-secondary-btn-background-color-disabled': 'var(--em-background-color-light)',
  '--em-secondary-btn-background-color-hover': 'var(--em-background-color-subtle)',
  '--em-secondary-btn-background-color-pressed': 'var(--em-background-color-muted)',
  '--em-secondary-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-secondary-btn-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-secondary-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-secondary-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-secondary-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-secondary-btn-label-color-default': 'var(--em-foreground-color-default)',
  '--em-secondary-btn-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-secondary-btn-label-font-medium-font-family': 'var(--em-font-family-default)',
  '--em-secondary-btn-label-font-medium-line-height': 'var(--em-line-height-md)',
  '--em-secondary-btn-label-font-medium-size': 'var(--em-font-size-sm)',
  '--em-secondary-btn-label-font-medium-weight': 'var(--em-font-weight-bold)',
  '--em-secondary-btn-label-font-small-font-family': 'var(--em-font-family-default)',
  '--em-secondary-btn-label-font-small-line-height': 'var(--em-line-height-sm)',
  '--em-secondary-btn-label-font-small-size': 'var(--em-font-size-xs)',
  '--em-secondary-btn-label-font-small-weight': 'var(--em-font-weight-medium)',
  '--em-secondary-btn-label-padding-default': 'var(--em-padding-200)',
  '--em-secondary-btn-padding-medium-bottom': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-medium-left': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-medium-right': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-medium-top': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-small-bottom': 'var(--em-padding-150)',
  '--em-secondary-btn-padding-small-left': 'var(--em-padding-150)',
  '--em-secondary-btn-padding-small-right': 'var(--em-padding-150)',
  '--em-secondary-btn-padding-small-top': 'var(--em-padding-150)',
  '--em-secondary-btn-size-medium-height': 'var(--em-height-1000)',
  '--em-secondary-btn-size-small-height': 'var(--em-height-800)',
  '--em-select-list-item-background-color-default': 'var(--em-background-color-neutral)',
  '--em-select-list-item-background-color-disabled': 'var(--em-background-color-neutral)',
  '--em-select-list-item-background-color-hover': 'var(--em-background-color-default)',
  '--em-select-list-item-background-color-pressed': 'var(--em-background-color-light)',
  '--em-select-list-item-background-color-selected': 'var(--em-background-color-inverted)',
  '--em-select-list-item-border-radius-default': 'var(--em-border-radius-200)',
  '--em-select-list-item-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-select-list-item-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-list-item-icon-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-list-item-icon-size-height': 'var(--em-height-400)',
  '--em-select-list-item-icon-size-width': 'var(--em-width-400)',
  '--em-select-list-item-isolate-background-color-default': 'var(--em-background-color-light)',
  '--em-select-list-item-isolate-background-color-hover': 'var(--em-background-color-muted)',
  '--em-select-list-item-isolate-border-radius-default': 'var(--em-border-radius-050)',
  '--em-select-list-item-isolate-external-padding-default': 'var(--em-padding-200)',
  '--em-select-list-item-isolate-label-color-default': 'var(--em-foreground-color-default)',
  '--em-select-list-item-isolate-label-font-font-family': 'var(--em-font-family-default)',
  '--em-select-list-item-isolate-label-font-line-height': 'var(--em-line-height-md)',
  '--em-select-list-item-isolate-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-list-item-isolate-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-select-list-item-isolate-padding-default': 'var(--em-padding-100)',
  '--em-select-list-item-isolate-size-height': 'var(--em-height-600)',
  '--em-select-list-item-label-padding-default': 'var(--em-padding-200)',
  '--em-select-list-item-left-label-color-default': 'var(--em-foreground-color-default)',
  '--em-select-list-item-left-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-list-item-left-label-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-list-item-left-label-font-font-family': 'var(--em-font-family-default)',
  '--em-select-list-item-left-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-select-list-item-left-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-list-item-left-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-select-list-item-padding-default': 'var(--em-padding-200)',
  '--em-select-list-item-right-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-select-list-item-right-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-list-item-right-label-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-list-item-right-label-font-font-family': 'var(--em-font-family-default)',
  '--em-select-list-item-right-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-select-list-item-right-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-list-item-right-label-font-weight': 'var(--em-font-weight-regular)',
  '--em-select-list-item-size-height': 'var(--em-height-800)',
  '--em-select-menu-background-color-default': 'var(--em-background-color-neutral)',
  '--em-select-menu-background-color-disabled': 'var(--em-background-color-neutral)',
  '--em-select-menu-background-color-focus': 'var(--em-background-color-neutral)',
  '--em-select-menu-background-color-hover': 'var(--em-background-color-default)',
  '--em-select-menu-background-color-pressed': 'var(--em-background-color-light)',
  '--em-select-menu-background-color-selected': 'var(--em-background-color-inverted)',
  '--em-select-menu-border-color-default': 'var(--em-background-color-muted)',
  '--em-select-menu-border-radius-default': 'var(--em-border-radius-200)',
  '--em-select-menu-border-width-default': 'var(--em-border-width-default)',
  '--em-select-menu-full-gap-default': 'var(--em-padding-050)',
  '--em-select-menu-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-select-menu-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-menu-icon-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-menu-icon-size-height': 'var(--em-height-400)',
  '--em-select-menu-icon-size-width': 'var(--em-width-400)',
  '--em-select-menu-label-color-default': 'var(--em-foreground-color-default)',
  '--em-select-menu-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-menu-label-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-menu-label-font-font-family': 'var(--em-font-family-default)',
  '--em-select-menu-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-select-menu-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-menu-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-select-menu-label-padding-default': 'var(--em-padding-200)',
  '--em-select-menu-list-background-color-default': 'var(--em-background-color-neutral)',
  '--em-select-menu-list-border-radius-default': 'var(--em-border-radius-300)',
  '--em-select-menu-list-gap-default': 'var(--em-padding-200)',
  '--em-select-menu-list-padding-default': 'var(--em-padding-200)',
  '--em-select-menu-list-size-max-height': '320px',
  '--em-select-menu-padding-default': 'var(--em-padding-300)',
  '--em-select-menu-size-height-default': 'var(--em-height-1000)',
  '--em-select-menu-size-width-max-width': '400px',
  '--em-select-menu-size-width-min-width': '64px',
  '--em-status-error': 'rgb(208 49 9)',
  '--em-switch-background-color-off': 'var(--em-background-color-subtle)',
  '--em-switch-background-color-on': 'var(--em-background-color-inverted)',
  '--em-switch-background-color-slider': 'var(--em-background-color-neutral)',
  '--em-switch-padding-default': 'var(--em-border-radius-050)',
  '--em-switch-size-height': 'var(--em-width-400)',
  '--em-switch-size-width': 'var(--em-width-800)',
  '--em-switch-slider-size-height': 'var(--em-width-300)',
  '--em-switch-slider-size-width': 'var(--em-width-300)',
  '--em-table-backround-color-default-cell': 'var(--em-background-color-neutral)',
  '--em-table-backround-color-default-header': 'var(--em-background-color-default)',
  '--em-table-backround-color-hover-cell': 'var(--em-background-color-light)',
  '--em-table-backround-color-hover-header': 'var(--em-background-color-subtle)',
  '--em-table-border-color-default': 'var(--em-background-color-subtle)',
  '--em-table-border-radius-default': 'var(--em-border-radius-300)',
  '--em-table-border-width-default': 'var(--em-border-width-default)',
  '--em-table-font-color-default': 'var(--em-foreground-color-default)',
  '--em-table-font-font-family': 'var(--em-font-family-default)',
  '--em-table-font-font-size': 'var(--em-font-size-xs)',
  '--em-table-font-font-weight-cell': 'var(--em-font-weight-regular)',
  '--em-table-font-font-weight-header': 'var(--em-font-weight-medium)',
  '--em-table-font-line-height': 'var(--em-line-height-sm)',
  '--em-table-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-table-icon-size-height': 'var(--em-icon-height)',
  '--em-table-icon-size-width': 'var(--em-icon-width)',
  '--em-table-padding-medium': 'var(--em-padding-200)',
  '--em-table-padding-small': 'var(--em-padding-100)',
  '--em-table-size-cell-height': 'var(--em-height-800)',
  '--em-table-size-label-height': 'var(--em-height-400)',
  '--em-table-size-min-width': 'var(--em-width-1600)',
  '--em-tabs-background-color-selected': 'var(--em-background-color-neutral)',
  '--em-tabs-background-color-unselected': 'var(--em-background-color-light)',
  '--em-tabs-border-radius-container': 'var(--em-border-radius-200)',
  '--em-tabs-border-radius-tab': 'var(--em-border-radius-150)',
  '--em-tabs-font-color-default': 'var(--em-foreground-color-default)',
  '--em-tabs-padding-container': 'var(--em-padding-050)',
  '--em-tabs-padding-tab': 'var(--em-padding-100)',
  '--em-text-input-background-color-default': 'var(--em-background-color-default)',
  '--em-text-input-background-color-disabled': 'var(--em-background-color-neutral)',
  '--em-text-input-background-color-filled': 'var(--em-background-color-default)',
  '--em-text-input-background-color-focused': 'var(--em-background-color-subtle)',
  '--em-text-input-background-color-hover': 'var(--em-background-color-subtle)',
  '--em-text-input-border-color-default': 'var(--em-background-color-muted)',
  '--em-text-input-border-color-error': 'var(--em-status-error)',
  '--em-text-input-border-radius-default': 'var(--em-border-radius-200)',
  '--em-text-input-border-width-default': 'var(--em-border-width-default)',
  '--em-text-input-border-width-error': 'var(--em-border-width-l)',
  '--em-text-input-icon-color-default': 'var(--em-foreground-color-muted)',
  '--em-text-input-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-text-input-icon-color-filled': 'var(--em-foreground-color-default)',
  '--em-text-input-icon-color-focused': 'var(--em-foreground-color-default)',
  '--em-text-input-icon-color-hover': 'var(--em-foreground-color-muted)',
  '--em-text-input-icon-size-height': 'var(--em-height-400)',
  '--em-text-input-icon-size-width': 'var(--em-width-400)',
  '--em-text-input-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-text-input-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-text-input-label-color-error': 'var(--em-status-error)',
  '--em-text-input-label-color-filled': 'var(--em-foreground-color-default)',
  '--em-text-input-label-color-focused': 'var(--em-foreground-color-default)',
  '--em-text-input-label-color-hover': 'var(--em-foreground-color-muted)',
  '--em-text-input-label-font-font-family': 'var(--em-font-family-default)',
  '--em-text-input-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-text-input-label-font-size': 'var(--em-font-size-xs)',
  '--em-text-input-label-font-weight-default': 'var(--em-font-weight-medium)',
  '--em-text-input-label-font-weight-placeholder': 'var(--em-font-weight-regular)',
  '--em-text-input-padding-default': 'var(--em-padding-200)',
  '--em-text-input-size-height': 'var(--em-height-1000)',
  '--em-text-input-size-max-width': '400px',
  '--em-text-input-size-min-width': '160px',
};

const stylesTypography = {
  '--em-font-family-default': 'inter',
  '--em-font-size-md': '16px',
  '--em-font-size-sm': '14px',
  '--em-font-size-xl': '20px',
  '--em-font-size-xs': '12px',
  '--em-font-size-xxl': '32px',
  '--em-font-weight-bold': '700',
  '--em-font-weight-medium': '500',
  '--em-font-weight-regular': '400',
  '--em-line-height-l': '19px',
  '--em-line-height-md': '16px',
  '--em-line-height-sm': '14px',
  '--em-line-height-xl': '38px',
};

const stylesShadow = {
  '--em-box-shadow-default-blur': '40px',
  '--em-box-shadow-default-color': 'rgb(33 33 41 / 25%)',
  '--em-box-shadow-default-position-x': '0px',
  '--em-box-shadow-default-position-y': '1px',
  '--em-box-shadow-default-spread': '0px',
};

type StylesColors = Record<keyof typeof stylesColors, string>;
type StylesSpacingAndSizes = Record<keyof typeof stylesSpacingAndSizes, string>;
type StylesBorders = Record<keyof typeof stylesBorders, string>;
type StylesComponents = Record<keyof typeof stylesComponents, string>;
type StylesTypography = Record<keyof typeof stylesTypography, string>;
type StylesShadow = Record<keyof typeof stylesShadow, string>;

export type Styles = StylesColors &
  StylesSpacingAndSizes &
  StylesBorders &
  StylesComponents &
  StylesTypography &
  StylesShadow;

export const styles: Styles = {
  ...stylesColors,
  ...stylesSpacingAndSizes,
  ...stylesBorders,
  ...stylesComponents,
  ...stylesTypography,
  ...stylesShadow,
};

export type StylesKeys = keyof typeof styles;
