export const themeColors = {
  '--em-gray-0': '#ffffff',
  '--em-gray-050': '#f7f7f8',
  '--em-gray-100': '#ededf1',
  '--em-gray-1000': '#000000',
  '--em-gray-200': '#e4e4ea',
  '--em-gray-300': '#d2d2d5',
  '--em-gray-400': '#b8b8bd',
  '--em-gray-500': '#909098',
  '--em-gray-600': '#727279',
  '--em-gray-700': '#5c5c66',
  '--em-gray-800': '#31313d',
  '--em-gray-900': '#212129',
  '--em-orange-050': '#ffeee6',
  '--em-orange-100': '#ffddcc',
  '--em-orange-200': '#ffccb3',
  '--em-orange-300': '#ffbb99',
  '--em-orange-400': '#ffaa80',
  '--em-orange-500': '#ff9966',
  '--em-orange-600': '#ff884d',
  '--em-orange-700': '#ff7733',
  '--em-orange-800': '#ff661a',
  '--em-orange-900': '#ff5400',
};

const themeSpacingAndSizes = {
  '--em-height-0': '0px',
  '--em-height-050': '2px',
  '--em-height-100': '4px',
  '--em-height-1000': '40px',
  '--em-height-1200': '48px',
  '--em-height-150': '6px',
  '--em-height-1600': '64px',
  '--em-height-200': '8px',
  '--em-height-2000': '80px',
  '--em-height-300': '12px',
  '--em-height-400': '16px',
  '--em-height-500': '20px',
  '--em-height-600': '24px',
  '--em-height-700': '28px',
  '--em-height-800': '32px',
  '--em-height-900': '36px',
  '--em-margin-0': '0px',
  '--em-margin-050': '2px',
  '--em-margin-100': '4px',
  '--em-margin-1000': '40px',
  '--em-margin-1200': '48px',
  '--em-margin-150': '6px',
  '--em-margin-1600': '64px',
  '--em-margin-200': '8px',
  '--em-margin-2000': '80px',
  '--em-margin-300': '12px',
  '--em-margin-400': '16px',
  '--em-margin-500': '20px',
  '--em-margin-600': '24px',
  '--em-margin-700': '28px',
  '--em-margin-800': '32px',
  '--em-margin-900': '36px',
  '--em-padding-0': '0px',
  '--em-padding-050': '2px',
  '--em-padding-100': '4px',
  '--em-padding-1000': '40px',
  '--em-padding-1200': '48px',
  '--em-padding-150': '6px',
  '--em-padding-1600': '64px',
  '--em-padding-200': '8px',
  '--em-padding-2000': '80px',
  '--em-padding-300': '12px',
  '--em-padding-400': '16px',
  '--em-padding-500': '20px',
  '--em-padding-600': '24px',
  '--em-padding-700': '28px',
  '--em-padding-800': '32px',
  '--em-padding-900': '36px',
  '--em-width-0': '0px',
  '--em-width-050': '2px',
  '--em-width-100': '4px',
  '--em-width-1000': '40px',
  '--em-width-1200': '48px',
  '--em-width-150': '6px',
  '--em-width-1600': '64px',
  '--em-width-200': '8px',
  '--em-width-2000': '80px',
  '--em-width-300': '12px',
  '--em-width-400': '16px',
  '--em-width-500': '20px',
  '--em-width-600': '24px',
  '--em-width-700': '28px',
  '--em-width-800': '32px',
  '--em-width-900': '36px',
};

const themeBorders = {
  '--em-border-radius-0': '0px',
  '--em-border-radius-050': '2px',
  '--em-border-radius-100': '4px',
  '--em-border-radius-150': '6px',
  '--em-border-radius-200': '8px',
  '--em-border-radius-300': '12px',
  '--em-border-radius-400': '32px',
  '--em-border-radius-500': '9999px',
  '--em-border-width-default': '1px',
  '--em-border-width-l': '2px',
  '--em-border-width-xl': '4px',
};

const themeComponents = {
  '--em-background-color-default': 'var(--em-gray-050)',
  '--em-background-color-inverted': 'var(--em-gray-900)',
  '--em-background-color-light': 'var(--em-gray-100)',
  '--em-background-color-muted': 'var(--em-gray-300)',
  '--em-background-color-neutral': 'var(--em-gray-0)',
  '--em-background-color-subtle': 'var(--em-gray-200)',
  '--em-card-border-radius-default': 'var(--em-border-radius-400)',
  '--em-card-empty-padding-default': 'var(--em-padding-300)',
  '--em-card-empty-subtitle-color-default': 'var(--em-foreground-color-muted)',
  '--em-card-empty-subtitle-font-line-height': 'var(--em-line-height-md)',
  '--em-card-empty-subtitle-font-size': 'var(--em-font-size-sm)',
  '--em-card-empty-subtitle-font-weight': 'var(--em-font-weight-regular)',
  '--em-card-empty-title-color-default': 'var(--em-foreground-color-default)',
  '--em-card-empty-title-font-line-height': 'var(--em-line-height-md)',
  '--em-card-empty-title-font-size': 'var(--em-font-size-sm)',
  '--em-card-empty-title-font-weight': 'var(--em-font-weight-medium)',
  '--em-card-error-padding-default': 'var(--em-padding-300)',
  '--em-card-error-state-icon-color-default': 'var(--em-status-error)',
  '--em-card-error-state-icon-size-height': 'var(--em-height-400)',
  '--em-card-error-state-icon-size-width': 'var(--em-width-400)',
  '--em-card-error-subtitle-color-default': 'var(--em-status-error)',
  '--em-card-error-subtitle-font-line-height': 'var(--em-line-height-md)',
  '--em-card-error-subtitle-font-size': 'var(--em-font-size-sm)',
  '--em-card-error-subtitle-font-weight': 'var(--em-font-weight-regular)',
  '--em-card-error-title-color-default': 'var(--em-status-error)',
  '--em-card-error-title-font-line-height': 'var(--em-line-height-md)',
  '--em-card-error-title-font-size': 'var(--em-font-size-sm)',
  '--em-card-error-title-font-weight': 'var(--em-font-weight-medium)',
  '--em-card-gap-default': 'var(--em-padding-800)',
  '--em-card-header-padding-default': 'var(--em-padding-100)',
  '--em-card-loader-border-radius-default': 'var(--em-border-radius-500)',
  '--em-card-loader-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-card-loader-icon-size-height': 'var(--em-height-600)',
  '--em-card-loader-icon-size-width': 'var(--em-width-600)',
  '--em-card-loader-padding-default': 'var(--em-padding-100)',
  '--em-card-padding-default': 'var(--em-padding-800)',
  '--em-card-subtitle-color-default': 'var(--em-foreground-color-muted)',
  '--em-card-subtitle-font-line-height': 'var(--em-line-height-sm)',
  '--em-card-subtitle-font-size': 'var(--em-font-size-sm)',
  '--em-card-subtitle-font-weight': 'var(--em-font-weight-regular)',
  '--em-card-title-color-default': 'var(--em-foreground-color-default)',
  '--em-card-title-font-line-height': 'var(--em-line-height-l)',
  '--em-card-title-font-size': 'var(--em-font-size-xl)',
  '--em-card-title-font-weight': 'var(--em-font-weight-bold)',
  '--em-card-title-padding-default': 'var(--em-padding-400)',
  '--em-categor-group-gap-default': 'var(--em-padding-200)',
  '--em-category-group-item-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-category-group-item-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-category-group-item-label-font-size': 'var(--em-font-size-xs)',
  '--em-category-group-item-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-category-indicator-border-radius-default': 'var(--em-border-radius-500)',
  '--em-category-indicator-color-default': 'var(--em-chart-color-1)',
  '--em-category-indicator-gap-default': 'var(--em-padding-100)',
  '--em-category-indicator-size-height': 'var(--em-width-300)',
  '--em-category-indicator-size-width': 'var(--em-width-300)',
  '--em-chart-color-1': 'var(--em-orange-900)',
  '--em-chart-color-10': 'var(--em-orange-050)',
  '--em-chart-color-2': 'var(--em-orange-800)',
  '--em-chart-color-3': 'var(--em-orange-700)',
  '--em-chart-color-4': 'var(--em-orange-600)',
  '--em-chart-color-5': 'var(--em-orange-500)',
  '--em-chart-color-6': 'var(--em-orange-400)',
  '--em-chart-color-7': 'var(--em-orange-300)',
  '--em-chart-color-8': 'var(--em-orange-200)',
  '--em-chart-color-9': 'var(--em-orange-100)',
  '--em-chart-gap-default': 'var(--em-padding-400)',
  '--em-chart-tooltip-background-color-default': 'var(--em-background-color-inverted)',
  '--em-chart-tooltip-border-radius-default': 'var(--em-border-radius-300)',
  '--em-chart-tooltip-gap-default': 'var(--em-padding-200)',
  '--em-chart-tooltip-label-color-default': 'rgb(255 255 255)',
  '--em-chart-tooltip-padding-default': 'var(--em-padding-400)',
  '--em-chart-tooltip-title-color-size': '0px',
  '--em-chart-tooltip-title-font-font-family': 'var(--em-font-family-default)',
  '--em-chart-tooltip-title-font-line-height': 'var(--em-line-height-md)',
  '--em-chart-tooltip-title-font-size': 'var(--em-font-size-sm)',
  '--em-chart-tooltip-title-font-weight': 'var(--em-font-weight-bold)',
  '--em-foreground-color-default': 'var(--em-gray-900)',
  '--em-foreground-color-error': 'var(--em-status-error)',
  '--em-foreground-color-inverted': 'var(--em-gray-0)',
  '--em-foreground-color-muted': 'var(--em-gray-700)',
  '--em-foreground-color-neutral': 'var(--em-gray-1000)',
  '--em-foreground-color-subtle': 'var(--em-gray-400)',
  '--em-icon-btn-bg-color-default': 'var(--em-background-color-light)',
  '--em-icon-btn-bg-color-disabled': 'var(--em-background-color-light)',
  '--em-icon-btn-bg-color-hover': 'var(--em-background-color-subtle)',
  '--em-icon-btn-bg-color-pressed': 'var(--em-background-color-muted)',
  '--em-icon-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-icon-btn-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-icon-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-icon-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-icon-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-icon-btn-padding-bottom': 'var(--em-padding-200)',
  '--em-icon-btn-padding-left': 'var(--em-padding-050)',
  '--em-icon-btn-padding-right': 'var(--em-padding-050)',
  '--em-icon-btn-padding-top': 'var(--em-padding-200)',
  '--em-icon-btn-size-height': 'var(--em-height-800)',
  '--em-icon-btn-size-width': 'var(--em-width-500)',
  '--em-icon-height': 'var(--em-height-400)',
  '--em-icon-width': 'var(--em-width-400)',
  '--em-label-background-color-default': 'var(--em-background-color-neutral)',
  '--em-label-border-radius-default': 'var(--em-border-radius-500)',
  '--em-label-label-font-color-default': 'var(--em-foreground-color-default)',
  '--em-label-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-label-label-font-size': 'var(--em-font-size-xs)',
  '--em-label-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-label-padding-left-right': 'var(--em-padding-100)',
  '--em-label-padding-top-bottom': 'var(--em-padding-050)',
  '--em-pie-chart-donut-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-pie-chart-donut-label-font-line-height': 'var(--em-line-height-md)',
  '--em-pie-chart-donut-label-font-size': 'var(--em-font-size-md)',
  '--em-pie-chart-donut-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-pie-chart-donut-number-color-default': 'var(--em-foreground-color-default)',
  '--em-pie-chart-donut-number-font-line-height': 'var(--em-line-height-xl)',
  '--em-pie-chart-donut-number-font-size': 'var(--em-font-size-xxl)',
  '--em-pie-chart-donut-number-font-weight': 'var(--em-font-weight-bold)',
  '--em-pie-chart-donut-number-gap-default': 'var(--em-padding-200)',
  '--em-primary-btn-bg-color-default': 'var(--em-foreground-color-muted)',
  '--em-primary-btn-bg-color-disabled': 'var(--em-background-color-light)',
  '--em-primary-btn-bg-color-hover': 'var(--em-foreground-color-default)',
  '--em-primary-btn-bg-color-pressed': 'var(--em-foreground-color-neutral)',
  '--em-primary-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-primary-btn-icon-color-default': 'var(--em-foreground-color-inverted)',
  '--em-primary-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-primary-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-primary-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-primary-btn-label-color-default': 'var(--em-foreground-color-inverted)',
  '--em-primary-btn-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-primary-btn-label-font-line-height': 'var(--em-line-height-md)',
  '--em-primary-btn-label-font-size': 'var(--em-font-size-sm)',
  '--em-primary-btn-label-font-weight': 'var(--em-font-weight-bold)',
  '--em-primary-btn-label-padding-left': 'var(--em-padding-200)',
  '--em-primary-btn-label-padding-right': 'var(--em-padding-200)',
  '--em-primary-btn-padding-bottom': 'var(--em-padding-300)',
  '--em-primary-btn-padding-left': 'var(--em-padding-300)',
  '--em-primary-btn-padding-left-2': 'var(--em-padding-300)',
  '--em-primary-btn-padding-right': 'var(--em-padding-300)',
  '--em-primary-btn-padding-top': 'var(--em-padding-300)',
  '--em-primary-btn-size-height': 'var(--em-height-1000)',
  '--em-secondary-btn-bg-color-default': 'var(--em-background-color-light)',
  '--em-secondary-btn-bg-color-disabled': 'var(--em-background-color-light)',
  '--em-secondary-btn-bg-color-hover': 'var(--em-background-color-subtle)',
  '--em-secondary-btn-bg-color-pressed': 'var(--em-background-color-muted)',
  '--em-secondary-btn-border-radius-default': 'var(--em-border-radius-500)',
  '--em-secondary-btn-icon-color-default': 'var(--em-foreground-color-default)',
  '--em-secondary-btn-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-secondary-btn-icon-size-height': 'var(--em-icon-height)',
  '--em-secondary-btn-icon-size-width': 'var(--em-icon-width)',
  '--em-secondary-btn-label-color-default': 'var(--em-foreground-color-default)',
  '--em-secondary-btn-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-secondary-btn-label-font-line-height': 'var(--em-line-height-md)',
  '--em-secondary-btn-label-font-size': 'var(--em-font-size-sm)',
  '--em-secondary-btn-label-font-weight': 'var(--em-font-weight-bold)',
  '--em-secondary-btn-label-padding-left': 'var(--em-padding-200)',
  '--em-secondary-btn-label-padding-right': 'var(--em-padding-200)',
  '--em-secondary-btn-padding-bottom': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-left': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-right': 'var(--em-padding-300)',
  '--em-secondary-btn-padding-top': 'var(--em-padding-300)',
  '--em-secondary-btn-size-height': 'var(--em-height-1000)',
  '--em-select-list-item-background-color-default': 'var(--em-background-color-neutral)',
  '--em-select-list-item-background-color-disabled': 'var(--em-background-color-neutral)',
  '--em-select-list-item-background-color-hover': 'var(--em-background-color-default)',
  '--em-select-list-item-background-color-pressed': 'var(--em-background-color-light)',
  '--em-select-list-item-background-color-selected': 'var(--em-background-color-inverted)',
  '--em-select-list-item-border-radius-default': 'var(--em-border-radius-200)',
  '--em-select-list-item-isolate-background-color-default': 'var(--em-background-color-light)',
  '--em-select-list-item-isolate-background-color-hover': 'var(--em-background-color-muted)',
  '--em-select-list-item-isolate-border-radius-default': 'var(--radius-050)',
  '--em-select-list-item-isolate-external-padding-default': 'var(--em-padding-200)',
  '--em-select-list-item-isolate-label-color-default': 'var(--em-foreground-color-default)',
  '--em-select-list-item-isolate-label-font-line-height': 'var(--em-line-height-md)',
  '--em-select-list-item-isolate-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-list-item-isolate-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-select-list-item-isolate-padding-default': 'var(--em-padding-100)',
  '--em-select-list-item-isolate-size-height': 'var(--em-height-600)',
  '--em-select-list-item-label-color-default': 'var(--em-foreground-color-default)',
  '--em-select-list-item-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-list-item-label-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-list-item-label-padding-default': 'var(--em-padding-200)',
  '--em-select-list-item-left-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-select-list-item-left-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-list-item-left-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-select-list-item-padding-default': 'var(--em-padding-200)',
  '--em-select-list-item-right-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-select-list-item-right-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-list-item-right-label-font-weight': 'var(--em-font-weight-regular)',
  '--em-select-list-item-size-height': 'var(--em-height-800)',
  '--em-select-menu-background-color-default': 'var(--em-background-color-neutral)',
  '--em-select-menu-background-color-disabled': 'var(--em-background-color-neutral)',
  '--em-select-menu-background-color-focus': 'var(--em-background-color-neutral)',
  '--em-select-menu-background-color-hover': 'var(--em-background-color-default)',
  '--em-select-menu-background-color-pressed': 'var(--em-background-color-light)',
  '--em-select-menu-background-color-selected': 'var(--em-background-color-inverted)',
  '--em-select-menu-border-color-default': 'var(--em-background-color-muted)',
  '--em-select-menu-border-radius-default': 'var(--em-border-radius-300)',
  '--em-select-menu-border-width-default': 'var(--em-border-width-default)',
  '--em-select-menu-icon-color-defaul': 'var(--em-foreground-color-default)',
  '--em-select-menu-icon-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-menu-icon-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-menu-icon-size-height': 'var(--em-height-400)',
  '--em-select-menu-icon-size-width': 'var(--em-width-400)',
  '--em-select-menu-label-color-default': 'var(--em-foreground-color-default)',
  '--em-select-menu-label-color-disabled': 'var(--em-foreground-color-subtle)',
  '--em-select-menu-label-color-selected': 'var(--em-foreground-color-inverted)',
  '--em-select-menu-label-font-line-height': 'var(--em-line-height-sm)',
  '--em-select-menu-label-font-size': 'var(--em-font-size-xs)',
  '--em-select-menu-label-font-weight': 'var(--em-font-weight-medium)',
  '--em-select-menu-label-padding-default': 'var(--em-padding-200)',
  '--em-select-menu-padding-default': 'var(--em-padding-300)',
  '--em-select-menu-search-background-color-default': 'var(--em-background-color-default)',
  '--em-select-menu-search-background-color-filled': 'var(--em-background-color-default)',
  '--em-select-menu-search-background-color-focused': 'var(--em-background-color-subtle)',
  '--em-select-menu-search-background-color-hover': 'var(--em-background-color-subtle)',
  '--em-select-menu-search-label-color-default': 'var(--em-foreground-color-muted)',
  '--em-select-menu-search-label-color-filled': 'var(--em-foreground-color-default)',
  '--em-select-menu-search-label-color-focused': 'var(--em-foreground-color-default)',
  '--em-status-error': 'rgb(208 49 9)',
};

const themeTypography = {
  '--em-font-size-md': '16px',
  '--em-font-size-sm': '14px',
  '--em-font-size-xl': '20px',
  '--em-font-size-xs': '12px',
  '--em-font-size-xxl': '32px',
  '--em-font-weight-bold': '700',
  '--em-font-weight-medium': '500',
  '--em-font-weight-regular': '400',
  '--em-line-height-l': '19px',
  '--em-line-height-md': '16px',
  '--em-line-height-sm': '14px',
  '--em-line-height-xl': '38px',
};

// NOTE: figma doest allow the export of css variables of font family
// Add this manully
const themeComponentsFontFamily = {
  '--em-label-label-font-family': 'Inter, sans-serif',
  '--em-category-indicator-group-label-family': 'Inter, sans-serif',
};

type ThemeColors = Record<keyof typeof themeColors, string>;
type ThemeSpacingAndSizes = Record<keyof typeof themeSpacingAndSizes, string>;
type ThemeBorders = Record<keyof typeof themeBorders, string>;
type ThemeComponents = Record<keyof typeof themeComponents, string>;
type ThemeTypography = Record<keyof typeof themeTypography, string>;
type ThemeComponentsFontFamily = Record<keyof typeof themeComponentsFontFamily, string>;

export type ThemeStyles = ThemeColors &
  ThemeSpacingAndSizes &
  ThemeBorders &
  ThemeComponents &
  ThemeTypography &
  ThemeComponentsFontFamily;

export const themeStyles: ThemeStyles = {
  ...themeColors,
  ...themeSpacingAndSizes,
  ...themeBorders,
  ...themeComponents,
  ...themeTypography,
  ...themeComponentsFontFamily,
};

export type ThemeStylesKeys = keyof typeof themeStyles;

export const themeChartBorderColors: string[] = [
  themeColors['--em-orange-900'],
  themeColors['--em-orange-800'],
  themeColors['--em-orange-700'],
  themeColors['--em-orange-600'],
  themeColors['--em-orange-500'],
  themeColors['--em-orange-400'],
  themeColors['--em-orange-300'],
  themeColors['--em-orange-200'],
  themeColors['--em-orange-100'],
  themeColors['--em-orange-050'],
];

export const themeChartColors: string[] = [
  themeColors['--em-orange-900'],
  themeColors['--em-orange-800'],
  themeColors['--em-orange-700'],
  themeColors['--em-orange-600'],
  themeColors['--em-orange-500'],
  themeColors['--em-orange-400'],
  themeColors['--em-orange-300'],
  themeColors['--em-orange-200'],
  themeColors['--em-orange-100'],
  themeColors['--em-orange-050'],
];
