export const themeColors = {
  '--gray-0': '#ffffff',
  '--gray-100': '#ededf1',
  '--gray-1000': '#000000',
  '--gray-200': '#e4e4ea',
  '--gray-300': '#d2d2d5',
  '--gray-400': '#b8b8bd',
  '--gray-50': '#f7f7f8',
  '--gray-500': '#909098',
  '--gray-600': '#727279',
  '--gray-700': '#5c5c66',
  '--gray-800': '#31313d',
  '--gray-900': '#212129',
  '--orange-100': '#ffddcc',
  '--orange-200': '#ffccb3',
  '--orange-300': '#ffbb99',
  '--orange-400': '#ffaa80',
  '--orange-50': '#ffeee6',
  '--orange-500': '#ff9966',
  '--orange-600': '#ff884d',
  '--orange-700': '#ff7733',
  '--orange-800': '#ff661a',
  '--orange-900': '#ff5400',
};

const themeSpacingAndSizes = {
  '--height-0': '0px',
  '--height-0,5': '2px',
  '--height-1': '4px',
  '--height-1,5': '6px',
  '--height-10': '40px',
  '--height-12': '48px',
  '--height-128': '512px',
  '--height-16': '64px',
  '--height-2': '8px',
  '--height-20': '80px',
  '--height-24': '96px',
  '--height-3': '12px',
  '--height-32': '128px',
  '--height-4': '16px',
  '--height-40': '160px',
  '--height-48': '192px',
  '--height-5': '20px',
  '--height-56': '224px',
  '--height-6': '24px',
  '--height-64': '256px',
  '--height-7': '28px',
  '--height-8': '32px',
  '--height-9': '36px',
  '--margin-0': '0px',
  '--margin-0,5': '2px',
  '--margin-1': '4px',
  '--margin-1,5': '6px',
  '--margin-10': '40px',
  '--margin-12': '48px',
  '--margin-16': '64px',
  '--margin-2': '8px',
  '--margin-20': '80px',
  '--margin-24': '96px',
  '--margin-3': '12px',
  '--margin-32': '128px',
  '--margin-4': '16px',
  '--margin-40': '160px',
  '--margin-48': '192px',
  '--margin-5': '20px',
  '--margin-56': '224px',
  '--margin-6': '24px',
  '--margin-64': '256px',
  '--margin-7': '28px',
  '--margin-8': '32px',
  '--margin-9': '36px',
  '--padding-0': '0px',
  '--padding-0,5': '2px',
  '--padding-1': '4px',
  '--padding-1,5': '6px',
  '--padding-10': '40px',
  '--padding-12': '48px',
  '--padding-16': '64px',
  '--padding-2': '8px',
  '--padding-20': '80px',
  '--padding-24': '96px',
  '--padding-3': '12px',
  '--padding-32': '128px',
  '--padding-4': '16px',
  '--padding-40': '160px',
  '--padding-48': '192px',
  '--padding-5': '20px',
  '--padding-56': '224px',
  '--padding-6': '24px',
  '--padding-64': '256px',
  '--padding-7': '28px',
  '--padding-8': '32px',
  '--padding-9': '36px',
  '--width-0': '0px',
  '--width-0,5': '2px',
  '--width-1': '4px',
  '--width-1,5': '6px',
  '--width-10': '40px',
  '--width-12': '48px',
  '--width-128': '512px',
  '--width-16': '64px',
  '--width-2': '8px',
  '--width-20': '80px',
  '--width-24': '96px',
  '--width-3': '12px',
  '--width-32': '128px',
  '--width-4': '16px',
  '--width-40': '160px',
  '--width-48': '192px',
  '--width-5': '20px',
  '--width-56': '224px',
  '--width-6': '24px',
  '--width-64': '256px',
  '--width-7': '28px',
  '--width-8': '32px',
  '--width-9': '36px',
};

const themeBorders = {
  '--border-0': '0px',
  '--border-2': '2px',
  '--border-4': '4px',
  '--border-default': '1px',
  '--rounded-2xl': '16px',
  '--rounded-3xl': '32px',
  '--rounded-default': '4px',
  '--rounded-full': '9999px',
  '--rounded-lg': '8px',
  '--rounded-md': '6px',
  '--rounded-none': '0px',
  '--rounded-sm': '2px',
  '--rounded-xl': '12px',
};

const themeComponents = {
  '--background-default': 'var(--gray-50)',
  '--background-inverted': 'var(--gray-900)',
  '--background-light': 'var(--gray-100)',
  '--background-muted': 'var(--gray-300)',
  '--background-neutral': 'var(--gray-0)',
  '--background-subtle': 'var(--gray-200)',
  '--categories-1': 'var(--orange-900)',
  '--categories-10': 'var(--orange-50)',
  '--categories-2': 'var(--orange-800)',
  '--categories-3': 'var(--orange-700)',
  '--categories-4': 'var(--orange-600)',
  '--categories-5': 'var(--orange-500)',
  '--categories-6': 'var(--orange-400)',
  '--categories-7': 'var(--orange-300)',
  '--categories-8': 'var(--orange-200)',
  '--categories-9': 'var(--orange-100)',
  '--foreground-default': 'var(--gray-900)',
  '--foreground-error': 'var(--status-error)',
  '--foreground-inverted': 'var(--gray-0)',
  '--foreground-muted': 'var(--gray-700)',
  '--foreground-neutral': 'var(--gray-1000)',
  '--foreground-subtle': 'var(--gray-400)',
  '--icn-btn-background-default': 'var(--background-light)',
  '--icn-btn-background-disabled': 'var(--background-light)',
  '--icn-btn-background-hover': 'var(--background-subtle)',
  '--icn-btn-background-pressed': 'var(--background-muted)',
  '--icn-btn-icon-default': 'var(--foreground-default)',
  '--icn-btn-icon-disabled': 'var(--foreground-subtle)',
  '--primary-btn-background-default': 'var(--foreground-muted)',
  '--primary-btn-background-disabled': 'var(--background-light)',
  '--primary-btn-background-hover': 'var(--foreground-default)',
  '--primary-btn-background-pressed': 'var(--foreground-neutral)',
  '--primary-btn-text-default': 'var(--foreground-inverted)',
  '--primary-btn-text-disabled': 'var(--foreground-subtle)',
  '--secondary-btn-background-default': 'var(--background-light)',
  '--secondary-btn-background-disabled': 'var(--background-light)',
  '--secondary-btn-background-hover': 'var(--background-subtle)',
  '--secondary-btn-background-pressed': 'var(--background-muted)',
  '--secondary-btn-text-default': 'var(--foreground-default)',
  '--secondary-btn-text-disabled': 'var(--foreground-subtle)',
  '--status-error': 'rgb(208 49 9)',
  '--toggle-bg-off': 'var(--background-subtle)',
  '--toggle-bg-on': 'var(--background-inverted)',
  '--toggle-thumb-default': 'var(--background-neutral)',
};

const themeTypography = {
  '--font-height-lg': '19px',
  '--font-height-md': '16px',
  '--font-height-sm': '14px',
  '--font-height-xl': '38px',
  '--font-size-4xl': '32px',
  '--font-size-default': '16px',
  '--font-size-sm': '14px',
  '--font-size-xs': '12px',
  '--font-weight-bold': '700',
  '--font-weight-medium': '500',
  '--font-weight-regular': '400',
};

type ThemeColors = Record<keyof typeof themeColors, string>;
type ThemeSpacingAndSizes = Record<keyof typeof themeSpacingAndSizes, string>;
type ThemeBorders = Record<keyof typeof themeBorders, string>;
type ThemeComponents = Record<keyof typeof themeComponents, string>;
type ThemeTypography = Record<keyof typeof themeTypography, string>;

export type ThemeStyles = ThemeColors &
  ThemeSpacingAndSizes &
  ThemeBorders &
  ThemeComponents &
  ThemeTypography &
  Record<string, string>;

export const themeStyles: ThemeStyles = {
  ...themeColors,
  ...themeSpacingAndSizes,
  ...themeBorders,
  ...themeComponents,
  ...themeTypography,
};

export const themeChartBorderColors: string[] = [
  themeColors['--orange-900'],
  themeColors['--orange-800'],
  themeColors['--orange-700'],
  themeColors['--orange-600'],
  themeColors['--orange-500'],
  themeColors['--orange-400'],
  themeColors['--orange-300'],
  themeColors['--orange-200'],
  themeColors['--orange-100'],
  themeColors['--orange-50'],
];

export const themeChartColors: string[] = [
  themeColors['--orange-900'],
  themeColors['--orange-800'],
  themeColors['--orange-700'],
  themeColors['--orange-600'],
  themeColors['--orange-500'],
  themeColors['--orange-400'],
  themeColors['--orange-300'],
  themeColors['--orange-200'],
  themeColors['--orange-100'],
  themeColors['--orange-50'],
];
